### ISSUE TITLE
css not stored in packed directory

### ISSUE THREAD

**Issue by AllanCochrane** [jhthorsen/mojolicious-plugin-bootstrap3#2]
# Remove all assets
```
$ rm packed/*
rm: cannot remove `packed/*': No such file or directory
```
# Restart hypnotoad
```
$ hypnotoad script/web_app
[BOOTSTRAP] Defining asset 'bootstrap.css' SASS_PATH=/local/brodie/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Mojolicious/Plugin/Bootstrap3/sass
[ASSETPACK] Adding Mojolicious::Plugin::AssetPack::Preprocessor::Scss preprocessor.
[ASSETPACK] Adding Mojolicious::Plugin::AssetPack::Preprocessor::JavaScript preprocessor.
[ASSETPACK] Adding Mojolicious::Plugin::AssetPack::Preprocessor::Css preprocessor.
Starting hot deployment for Hypnotoad server 342.
```
# What's been generated?
```
$ ls packed
bootstrap-4509cc77322830203b41c34a66bd1066.min.js  datatables-aca9feb0d7615cd84b92fececbfd6815.min.js  datatables-f50b171673c6af120f6012ebcb16e733.min.css
```
Where is the packed/bootstrap-ca9500011758c86475e279b5939ab3b0.css file that the HTML references?

I can find it in the local install:
```
$ ls -l ~/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Mojolicious/Plugin/Bootstrap3/packed/bootstrap-ca9500011758c86475e279b5939ab3b0.css
-r--r--r-- 1 brodie brodie 119123 Mar 16 12:50 /local/brodie/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Mojolicious/Plugin/Bootstrap3/packed/bootstrap-ca9500011758c86475e279b5939ab3b0.css
```

The settings for bootstrap3 are:
```perl
  # Plugins & Configuration
  $self->plugin( bootstrap3 => {
    css => [qw( bootstrap.scss )],
    js => [qw(alert.js modal.js tooltip.js popover.js)],
    jquery => 1,
   });
```
# Versions

```
$ grep -i version ~/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Mojolicious/Plugin
...
our $VERSION = '3.3006';

$ grep -i version ~/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Mojolicious/Plugin/AssetPack.pm
our $VERSION = '0.49';

$ mojo version
CORE
  Perl        (v5.20.1, linux)
  Mojolicious (6.07, Clinking Beer Mugs)

OPTIONAL
  EV 4.0+                 (n/a)
  IO::Socket::Socks 0.64+ (n/a)
  IO::Socket::SSL 1.94+   (n/a)
  Net::DNS::Native 0.15+  (n/a)

This version is up to date, have fun!
```
The sass program is not installed. 

CSS::Minifier::XS is installed (0.09)

**Comment by jhthorsen** [comment]
Have you done any customization to bootstrap.scss? If you haven't, there won't be any .css files generated, but rather the bundled file will be used:

https://github.com/jhthorsen/mojolicious-plugin-bootstrap3/tree/master/lib/Mojolicious/Plugin/Bootstrap3/packed

**Comment by AllanCochrane** [comment]
No, no customisation that I am aware of, how could I tell if I have inadvertently changed bootstrap.scss?

I don't have a copy in my app directory tree.

I just forced a cpanm reinstall of Bootstrap3 and still don't get the distribution's .css file. Wierd. Works OK under morbo though.

Even more strangely if I initialise the plugin like:

```
$self->plugin('bootstrap3');
```

and run it under hypnotoad then neither .css not .js from distribution are put into packed/

**Comment by jhthorsen** [comment]
@AllanCochrane: There's many ways to change bootstrap.scss, but you would know it if you did any customization.

So... Files in *your* packed directory will only be created, if no other packed file is found. So in this case, AssetPack will find the already generated .css file, and therefor not create a file in your packed directory.

You can see how this works here: https://github.com/jhthorsen/mojolicious-plugin-bootstrap3/blob/master/lib/Mojolicious/Plugin/Bootstrap3.pm#L267
What happens is that ```asset_path()``` is pushed to the static search path of your application, which again will find these files https://github.com/jhthorsen/mojolicious-plugin-bootstrap3/tree/master/lib/Mojolicious/Plugin/Bootstrap3/packed, instead of generating a new asset.

So that's why you won't see any assets in *your* ```public/packed``` directory.

**Comment by AllanCochrane** [comment]
Ok, understood.

My issue is that I am running Hypnotoad behind an Apache proxy and Apache is set to serve the static assets for the application rather than having them be served by Hypnotoad. The Apache process has no read access to the Mojolicious/Plugin/Bootstrap3/packed directory tree so obviously couldn't find them and setting asset_path had no effect because the web request was never hitting Hypnotoad...

**Comment by jhthorsen** [comment]
I would suggest just using bootstrap from a cdn, if you're using it unmodified. Something like this:

```
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
```

If that's not what you want, you can always copy the assets manually to "public/packed":
```
cp $(perl -MMojolicious::Plugin::Bootstrap3 -le'print Mojolicious::Plugin::Bootstrap3->asset_path')/packed/* public/packed/
```
