### ISSUE TITLE
Impossible to include jQuery without any of Bootstrap Plugins

### ISSUE THREAD

**Issue by zoffixznet** [jhthorsen/mojolicious-plugin-bootstrap3#7]
[This condition](https://github.com/jhthorsen/mojolicious-plugin-bootstrap3/blob/master/lib/Mojolicious/Plugin/Bootstrap3.pm#L357) should be changed to simple `if ( $config->{js} ) {...}` instead of a deref too.

Currently, it's impossible to include jQuery without any of the Bootstrap3 JS plugins. On my current site, I use Bootstrap and have some custom JS code that uses jQuery. It would be nice if I could get jQuery for free from the Bootstrap plugin instead of adding a URL manually; especially since I expect to eventually to need at least *some* Bootstrap plugins included as well.

**Comment by jhthorsen** [comment]
Would this work for you instead?

    plugin Bootstrap3 => {jquery => 1};

Right now this defaults to "1", but I could simply include jQuery no-matter if specified when loading the plugin.

**Comment by zoffixznet** [comment]
So jQuery would be loaded with it's set to 1 (which is the default)? That'll work

**Comment by jhthorsen** [comment]
No, you need to actively set {jquery => 1}. Please see the commits above.

Let me know if this works for you.

**Comment by zoffixznet** [comment]
Yeah, that's perfect!  Thanks

**Comment by jhthorsen** [comment]
Sweet :+1: 

On it's way to CPAN now.

Note: The new version even has the latest bootstrap bundled: https://github.com/twbs/bootstrap/tree/v3.3.6
